name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - name: Build and tag Docker image
        run: docker build -t department-service:v1 .

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted]
    env:
      APP_PORT: 8083
      DB_URL: "jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC"
      DB_USERNAME: user2
      DB_PASSWORD: PassWord1234@
    steps:
      - name: Stop and remove existing containers
        run: docker compose down || true

      - name: Run with Docker Compose
        run: docker compose up -d
